### ISSUE TITLE
Removal of version 1.0.1 from npm/yarn registry breaks existing builds

### ISSUE THREAD

**Issue by dpsoccerdude101** [lilibraries/hooks#2]
### Description
Our team recently discovered that our builds started failing due to the unavailability of version 1.0.1 of `@lilib/hooks` on both npm and yarn package registries. It appears this version has been removed or is no longer accessible. This sudden removal has impacted our production builds and releases.

### Steps to Reproduce
1. Run `yarn add @lilib/hooks@1.0.1` or `npm install @lilib/hooks@1.0.1`.
2. Observe the error indicating that version 1.0.1 is not found in the registry.

### Expected Behavior
Previously, running `yarn add @lilib/hooks@1.0.1` or `npm install @lilib/hooks@1.0.1` would successfully install version 1.0.1 of `@lilib/hooks`.

### Actual Behavior
The mentioned commands now return an error, something akin to:
`error An unexpected error occurred: "https://registry.yarnpkg.com/@lilib/hooks/-/hooks-1.0.1.tgz: Request failed \"404 Not Found\"".`

### Additional Context
The removal of this version has affected our CI/CD pipelines and production builds. We had dependencies explicitly set to version 1.0.1 due to specific features or bug fixes that were pertinent to our project's functionality.

### Potential Solutions or Next Steps
- Could the maintainers provide any context on why this version was removed?
- Is there a recommended upgrade path or alternative version we should use that is a direct substitute for version 1.0.1?
- If this removal was unintentional, can version 1.0.1 be republished?

We understand that managing open-source projects is challenging and appreciate all the work that goes into `@lilib/hooks`. Any guidance or assistance regarding this matter would be greatly appreciated.

Thank you!

**Comment by LeeWeisheng** [comment]
I'm sorry, I mistakenly deleted version 1.0.1 when replacing the automatic publishing tool. You can use version 1.0.3 to replace it.

**Comment by dpsoccerdude101** [comment]
Thank you for getting back to me so quickly, @LeeWeisheng.

I understand these things can happen, especially when dealing with tooling changes. I appreciate you suggesting a workaround. We'll update our dependencies to use version 1.0.3, as recommended.

Please ensure that future deletions of versions are communicated in advance or documented in the release notes to prevent similar disruptions. This would greatly assist us in planning our build cycles and dependencies better.

Thanks again for your assistance and the great work on @lilib/hooks!

**Comment by LeeWeisheng** [comment]
Okay, I will be careful with version releases in the future.
